name: Build Echo

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap version file
        run: echo 0 > src/version.txt
        shell: pwsh

      - name: Configure (32-bit)
        run: cmake -B build -A Win32

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Upload built DLL
        uses: actions/upload-artifact@v4
        with:
          name: Echo-dll
          path: build/Release/*.dll
          if-no-files-found: error
